### ISSUE TITLE
Issue with gnuplot

### ISSUE THREAD

**Issue by TLESORT** [TLESORT/Baxter_Learning#2]
Hi, 
I have a problem with gnuplot at : 

	printing.lua:92: in function 'show_figure'
	script.lua:94: in function 'train_Epoch'
	script.lua:161: in main chunk

The error is : 

cannot open </usr/bin/gnuplot -persist > /dev/null 2>&1> in mode  w.  This might be because eg the executable doesn't exist, but it could also be because you are out of memory. at /home/tim/torch/pkg/torch/lib/TH/THDiskFile.c:774

stack traceback:
	[C]: at 0x7fa00da4ebe0
	[C]: in function 'PipeFile'
	/home/tim/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:134: in function 'getfigure'
	/home/tim/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:747: in function 'filefigure'
	/home/tim/torch/install/share/lua/5.1/gnuplot/gnuplot.lua:754: in function 'epsfigure'
	/home/tim/torch/install/share/lua/5.1/optim/Logger.lua:180: in function 'plot'
	/home/tim/Baxter_Learning/printing.lua:92: in function 'show_figure'
	script.lua:94: in function 'train_Epoch'
	script.lua:161: in main chunk
	[C]: in function 'dofile'
	[string "_RESULT={dofile('script.lua')}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/tim/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	.../tim/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00405d50`

I reduced the batch size at 2.
I a m trying to figure out if it is a memory problem but with a batch size of 2 and 4 Go of video memory, it is strange.
Maybe a ram pb...

Do you have any idea? Maybe all the images should not be loaded at one time at the beginning of the program.

**Comment by Mathieu-Seurin** [comment]
I cannot reproduce the bug on my machine.

About the memory, based on htop statistics, you don't need more than 3 gb of ram to execute the program (on cpu) and since the batch size is reduced to 2 images, GPU memory shouldn't be a problem ...

Can you import gnuplot on his own ?
> require 'gnuplot'
> x=torch.linspace(-2*math.pi,2*math.pi)
> gnuplot.plot(torch.sin(x))

**Comment by TLESORT** [comment]
Yes it works

**Comment by Mathieu-Seurin** [comment]
I'm kinda stuck.
If you set plot = false (line 67 in script.lua), can you run the whole program ?

**Comment by TLESORT** [comment]
I asked to much to my computer...  , by closing everything else I am able to execute the program.

Thank you for your help ^^
