### ISSUE TITLE
Error when batch size=2 and Epoch=1

### ISSUE THREAD

**Issue by TLESORT** [TLESORT/Baxter_Learning#3]
Small issue I think, but at the sixth step of cross-validation, there is a error when batch size is set at 2 and epoch at 1:

        bad argument #3 to '?' (torch.*Tensor expected, got nil)
        stack traceback:
	[C]: at 0x7fe40a31e0d0
	[C]: in function '__newindex'
	/home/tim/Baxter_Learning/functions.lua:122: in function 'getRandomBatch'
	script.lua:118: in function 'train_Epoch'
	script.lua:161: in main chunk
	[C]: in function 'dofile'
	[string "_RESULT={dofile('script.lua')}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/tim/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	.../tim/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00405d50

Cheers

**Comment by Mathieu-Seurin** [comment]
With torch.manualSeed(1337) ?
with 'data' or 'moreData' folder ?

**Comment by TLESORT** [comment]
It was with 123, I double checked and it seems that my last "git pull", had failed.
It works now :)
My bad ;)

**Comment by Mathieu-Seurin** [comment]
You'll still get problems because i modifyied the rewarded_Joint in get_one_random_Caus_Set line 228
Should be 0.8 -0.8 for the 'data' dataset

and -1.3, 1.3 for my 'moreData' dataset

EDIT : Next pull request fix that
